### ISSUE TITLE
Mykrobe installed via pip doesn't give any results

### ISSUE THREAD

**Issue by flashton2003** [Mykrobe-tools/mykrobe#64]
Hello!

I'm trying to run mykrobe on Ubuntu 16.04, installed via git clone and pip3 as per the instructions.

Then, when I run 

`mykrobe predict 9998 tb -1 tb_volume/oucru_robot/9998-17107_S14/9998-17107_S14_1.fastq.gz`

The only output I get is

`INFO:mykrobe.cmds.amr:Running AMR prediction with panels data/panels/tb-species-170421.fasta.gz, data/panels/tb-hunt-probe-set-jan-03-2019.fasta.gz`

and then back to command prompt. No error or anything. No output files written.

The panels are in, what i assume is the correct place e.g. `/home/ubuntu/.local/lib/python3.5/site-packages/mykrobe/data/panels/tb-species-170421.fasta.gz`.

Any thoughts?

Thanks,

Phil

**Comment by mbhall88** [comment]
How big is the fastq file? Would you be able to share it so we can take a look?

I have you been able to successfully run on other files?

**Comment by flashton2003** [comment]
FASTQ file is 90 Mb, here is a dropbox link.

https://www.dropbox.com/s/3yakk2aovpbcz2j/9998-17107_S14_1.fastq.gz?dl=0

No, haven't been able to run successfully (but the docker container worked, as per other thread).

**Comment by mbhall88** [comment]
An update @flashton2003 : I have been able to recreate this issue. Will hopefully get a fix for you soon.

**Comment by mbhall88** [comment]
Ok, so the issue is that `pip` is silently failing to copy the `mccortex31` binary into `/usr/local/bin`. If you install with `pip3 install -vvv .` you will see the error message in the log eventually.
The reason for this is if you are installing using `pip` **outside** of a virtual environment, it will try and put `mccortex31` into `/usr/local/bin`. See this line of code

https://github.com/Mykrobe-tools/mykrobe/blob/cee6b8159eb313e98a95934cb662593698c76385/setup.py#L33

So there are two fixes:
1. Install with `sudo pip3 install .` 
2. Install inside a virtual environment.

I would recommend Option 2, but it is obviously up to you. I was able to very easily install using [`pipenv`](https://pipenv.readthedocs.io/en/latest/).

Let me know how you get on.

**Comment by flashton2003** [comment]
Option 2 worked well, thanks for the fix.
