### ISSUE TITLE
Meaning of lower case 'r' for resistance

### ISSUE THREAD

**Issue by flashton2003** [Mykrobe-tools/mykrobe#84]
Hello,

I've noticed that some variants e.g. rrs_C1402X-C1473247A:239:236:669 for capreomycin are reported with a lower case 'r' in the susceptibility column.

I guess this means that the association is uncertain? Can you confirm?

Thanks,

Phil

p.s. loving the new version, installed via conda and everything working well!

**Comment by martinghunt** [comment]
Hi Phil,

Lower case "r" means it's a minor allele call. If you check the "coverage" section of the JSON output you should see most of the "median_depth" is on the ref allele, but there is enough on the alt to trigger an "r" call instead of "S". There's a discussion of them in the wellcome manuscript - see the "Minor alleles improve prediction" section. https://wellcomeopenresearch.org/articles/4-191

Martin

**Comment by flashton2003** [comment]
Great, thanks for the clarification!

**Comment by iqbal-lab** [comment]
Hey @flashton2003  - minor alleles at the rrs genes are sometimes due to contamination from other nasopharyngeal flora. My hope was that by demanding exact matches for entire k-mers, we reduced the risk of such false positives in Mykrobe. We have previously seen such false positives from SNP callers on a given fastq, which are not made by Mykrobe. But nevertheless, i would view with caution. You can always try filtering reads for the correct species via Kraken (or the clockwork decontamination approach, which i think is better)

**Comment by flashton2003** [comment]
Interesting, thanks Zam!
